// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using LottoDataManager.Includes.Utilities;

namespace LottoDataManager.Includes.Classes.ML.FastTree
{
    public class FastTreeTrainer: MLModelBuilderAbstract
    {
        private static string MODEL_FILE = FastTreePredictor.MLNetModelPath;
        private static string OUTPUT_COLUMN_NAME = "RESULT";

        // Create MLContext to be shared across the model creation workflow objects 
        // Set a random seed for repeatable/deterministic results across multiple trainings.
        private static MLContext mlContext = new MLContext(seed: 1);

        public override void CreateModel(String mlDataSetsPath)
        {
            // Load Data
            InvokeProcessingStatus(ResourcesUtils.GetMessage("mac_lrn_bldr_log_1"));
            IDataView trainingDataView = mlContext.Data.LoadFromTextFile<FastTreeInputModel>(
                                            path: @mlDataSetsPath,
                                            hasHeader: true,
                                            separatorChar: ',',
                                            allowQuoting: true,
                                            allowSparse: false);
            // Build training pipeline
            InvokeProcessingStatus(ResourcesUtils.GetMessage("mac_lrn_bldr_log_2"));
            IEstimator<ITransformer> trainingPipeline = BuildTrainingPipeline(mlContext);

            // Train Model
            InvokeProcessingStatus(ResourcesUtils.GetMessage("mac_lrn_bldr_log_3"));
            ITransformer mlModel = RetrainModel(mlContext, trainingDataView, trainingPipeline);

            // Evaluate quality of Model
            InvokeProcessingStatus(ResourcesUtils.GetMessage("mac_lrn_bldr_log_4"));
            Evaluate(mlContext, trainingDataView, trainingPipeline, OUTPUT_COLUMN_NAME);

            // Save model
            InvokeProcessingStatus("\r\n\r\n\r\n" + ResourcesUtils.GetMessage("mac_lrn_bldr_log_5"));
            SaveModel(mlContext, mlModel, MODEL_FILE, trainingDataView.Schema);
        }

        public IEstimator<ITransformer> BuildTrainingPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations 
            var dataProcessPipeline = mlContext.Transforms.Categorical.OneHotHashEncoding(new[] { new InputOutputColumnPair("game_cd", "game_cd") })
                                      .Append(mlContext.Transforms.Text.FeaturizeText("draw_date_tf", "draw_date"))
                                      .Append(mlContext.Transforms.Concatenate("Features", new[] { "game_cd", "draw_date_tf", "num1", "num2", "num3", "num4", "num5", "num6" }));
            // Set the training algorithm 
            var trainer = mlContext.Regression.Trainers.FastTree(new FastTreeRegressionTrainer.Options() { NumberOfLeaves = 19, MinimumExampleCountPerLeaf = 10, NumberOfTrees = 500, LearningRate = 0.09198709f, Shrinkage = 0.2990312f, LabelColumnName = @"RESULT", FeatureColumnName = "Features" });

            var trainingPipeline = dataProcessPipeline.Append(trainer);

            return trainingPipeline;
        }
    }
}
