// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML.Data;

namespace LottoDataManager.Includes.Classes.ML.FastTree
{
    public class ModelOutputFastTree
    {
        public float Score { get; set; }
    }
}
