// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML.Data;

namespace LottoDataManager.Includes.Classes.ML.SDCARegression
{
    public class SDCARegressionOutputModel
    {
        public float Score { get; set; }
    }
}
