// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LottoDataManager.Includes.Classes.Reports.Templates.Fragments
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\DashboardBox_Fragment.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class DashboardBox_Fragment : IndividualGameHTMLReportView
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n<div class=\"dashboard-box\">\r\n    <div class=\"dashboard-box-content\">\r\n        <" +
                    "div class=\"title-partition\">\r\n            <div class=\"dashboard-box-title\">\r\n   " +
                    "             ");
            
            #line 7 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\DashboardBox_Fragment.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ProfitAndLossReport.ReportTitle));
            
            #line default
            #line hidden
            this.Write("\r\n            </div>\r\n            <div class=\"dashboard-box-sub-title\">\r\n        " +
                    "        Profit and Loss Report\r\n            </div>\r\n            <div class=\"dash" +
                    "board-box-sub-title-combine\">\r\n                ");
            
            #line 13 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\DashboardBox_Fragment.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ProfitAndLossReport.ReportTitleGameList));
            
            #line default
            #line hidden
            this.Write("\r\n            </div>\r\n        </div>\r\n        <div class=\"title-partition\">\r\n    " +
                    "        <div class=\"dashboard-box-winnings\">\r\n                ");
            
            #line 18 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\DashboardBox_Fragment.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ProfitAndLossReport.LifeTimeWinnings));
            
            #line default
            #line hidden
            this.Write("\r\n            </div>\r\n            <div class=\"dashboard-box-sub-winnings\">\r\n     " +
                    "           Lifetime Winnings\r\n            </div>\r\n        </div>\r\n    </div>\r\n</" +
                    "div>\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
