// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LottoDataManager.Includes.Classes.Reports.Templates.Fragments.ReportBox
{
    using LottoDataManager.Includes.Model.Details;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\Claims_Fragment.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class Claims_Fragment : IndividualGameHTMLReportView
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"
<div class=""outline-container"">
    <div class=""outline-title"">
        <span class=""title-keyword"">Claims</span>
        <span class=""title-description"">- Total money you win and gotcha</span>
    </div>
    <div class=""outline-content"">
        <table class=""default-table"" cellspacing=""5"">
            <tbody>
                <tr>
                    <td>Total number of claims pending: </td>
                    <td>");
            
            #line 18 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\Claims_Fragment.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ProfitAndLossReport.TotalNumberOfClaims));
            
            #line default
            #line hidden
            this.Write(" claims</td>\r\n                </tr>\r\n                <tr>\r\n                    <t" +
                    "d>Total number of claims yet to redeem: </td>\r\n                    <td>");
            
            #line 22 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\Claims_Fragment.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ProfitAndLossReport.TotalNumberOfClaimsToRedeem));
            
            #line default
            #line hidden
            this.Write(" out of ");
            
            #line 22 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\Claims_Fragment.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ProfitAndLossReport.TotalNumberOfClaims));
            
            #line default
            #line hidden
            this.Write(" claims</td>\r\n                </tr>\r\n                <tr>\r\n                    <t" +
                    "d>Details of the claims</td>\r\n                    <td>\r\n                        " +
                    "");
            
            #line 27 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\Claims_Fragment.tt"
 foreach (var item in ProfitAndLossReport.ClaimDetailsList) { 
            
            #line default
            #line hidden
            this.Write("                             <div class=\"claims-details-breakdown\">\r\n            " +
                    "                    <span>");
            
            #line 29 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\Claims_Fragment.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Key));
            
            #line default
            #line hidden
            this.Write("</span>\r\n                                ");
            
            #line 30 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\Claims_Fragment.tt"
 foreach (LotteryBet bet in (List<LotteryBet>) item.Value) { 
            
            #line default
            #line hidden
            this.Write("                                    <div>\r\n                                      " +
                    "  ");
            
            #line 32 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\Claims_Fragment.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bet.GetTargetDrawDateFormatted()));
            
            #line default
            #line hidden
            this.Write(" - \r\n                                        ");
            
            #line 33 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\Claims_Fragment.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bet.GetGNUFormat()));
            
            #line default
            #line hidden
            this.Write(",\r\n                                        ");
            
            #line 34 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\Claims_Fragment.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bet.GetLotteryWinningBet().GetWinningAmountInCurrency()));
            
            #line default
            #line hidden
            this.Write("\r\n                                        ");
            
            #line 35 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\Claims_Fragment.tt"
 if(!bet.GetLotteryWinningBet().IsClaimed()) { 
            
            #line default
            #line hidden
            this.Write("                                            , to redeem\r\n                        " +
                    "                ");
            
            #line 37 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\Claims_Fragment.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                                    </div>\r\n                                ");
            
            #line 39 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\Claims_Fragment.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                            </div>\r\n                        ");
            
            #line 41 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\Claims_Fragment.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                    </td>\r\n                </tr>\r\n            </tbody>\r\n        <" +
                    "/table>\r\n    </div>\r\n</div>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
