// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LottoDataManager.Includes.Classes.Reports.Templates.Fragments.ReportBox
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\OutletTally_Fragment.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class OutletTally_Fragment : IndividualGameHTMLReportView
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"<div class=""outline-container"">
    <div class=""outline-title"">
        <span class=""title-keyword"">Outlet Tally</span>
        <span class=""title-description"">- Your favorite outlet and your winning counts</span>
    </div>
    <div class=""outline-content"">
        <table class=""table-stats-style"" cellspacing=""0"">
            <thead>
                <th>Outlet where you bet</th>
                <th>Total Spending</th>
                <th>1 Digit Win</th>
                <th>2 Digit Win</th>
                <th>3 Digit Win</th>
                <th>4 Digit Win</th>
                <th>5 Digit Win</th>
                <th>6 Digit Win</th>
            </thead>
            <tbody>
                ");
            
            #line 20 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\OutletTally_Fragment.tt"
 foreach (var item in ProfitAndLossReport.AllBetsInTabularModeOutlet) { 
            
            #line default
            #line hidden
            this.Write("                     <tr>\r\n                        <td>");
            
            #line 22 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\OutletTally_Fragment.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item[0]));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                        <td>");
            
            #line 23 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\OutletTally_Fragment.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(double.Parse(item[1]).ToString("C")));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\r\n                        ");
            
            #line 25 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\OutletTally_Fragment.tt"
 for (int x=2; x<=(item.Length-1); x++) { 
            
            #line default
            #line hidden
            this.Write("                            ");
            
            #line 26 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\OutletTally_Fragment.tt"
 if(double.Parse(item[x])==0) { 
            
            #line default
            #line hidden
            this.Write("                                <td class=\"zero-sum-color\">\r\n                    " +
                    "        ");
            
            #line 28 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\OutletTally_Fragment.tt"
 }else{ 
            
            #line default
            #line hidden
            this.Write("                                <td>\r\n                            ");
            
            #line 30 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\OutletTally_Fragment.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                            ");
            
            #line 31 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\OutletTally_Fragment.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item[x]));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                        ");
            
            #line 32 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\OutletTally_Fragment.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                    </tr>\r\n                ");
            
            #line 34 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\OutletTally_Fragment.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            </tbody>\r\n        </table>\r\n    </div>\r\n</div>\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
