// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LottoDataManager.Includes.Classes.Reports.Templates.Fragments.ReportBox
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\Spending_Fragment.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class Spending_Fragment : IndividualGameHTMLReportView
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("<div class=\"outline-container\">\r\n    <div class=\"outline-title\">\r\n        <span c" +
                    "lass=\"title-keyword\">");
            
            #line 4 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\Spending_Fragment.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LBL("pal_form_labels_rpt_box_spending_1")));
            
            #line default
            #line hidden
            this.Write("</span>\r\n        <span class=\"title-description\">");
            
            #line 5 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\Spending_Fragment.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LBL("pal_form_labels_rpt_box_spending_2")));
            
            #line default
            #line hidden
            this.Write("</span>\r\n    </div>\r\n    <div class=\"outline-content\">\r\n        <table class=\"def" +
                    "ault-table\" cellspacing=\"5\">\r\n            <tbody>\r\n                <tr>\r\n       " +
                    "             <td>");
            
            #line 11 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\Spending_Fragment.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LBL("pal_form_labels_rpt_box_spending_3")));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                    <td>");
            
            #line 12 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\Spending_Fragment.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ProfitAndLossReport.TotalMoneySpentSoFar));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                </tr>\r\n                <tr>\r\n                    <td>");
            
            #line 15 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\Spending_Fragment.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LBL("pal_form_labels_rpt_box_spending_4")));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                    <td>");
            
            #line 16 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\Spending_Fragment.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ProfitAndLossReport.TotalMoneyLooseSoFar));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                </tr>\r\n                <tr>\r\n                    <td>");
            
            #line 19 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\Spending_Fragment.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LBL("pal_form_labels_rpt_box_spending_5")));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                    <td>");
            
            #line 20 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\Spending_Fragment.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ProfitAndLossReport.TotalMoneyBettedYearlyAverage));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                </tr>\r\n            </tbody>\r\n        </table>\r\n    </div>\r" +
                    "\n</div>\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
