// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LottoDataManager.Includes.Classes.Reports.Templates.Fragments.ReportBox
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\TallyBehavior_Fragment.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class TallyBehavior_Fragment : IndividualGameHTMLReportView
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"<div class=""outline-container"">
    <div class=""outline-title"">
        <span class=""title-keyword"">Tally Behavior</span>
        <span class=""title-description"">- Counting your specific behavior on betting</span>
    </div>
    <div class=""outline-content"">
        <table class=""default-table"" cellspacing=""5"">
            <tbody>
                <tr>
                    <td>How many bets you made so far?</td>
                    <td>");
            
            #line 12 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\TallyBehavior_Fragment.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ProfitAndLossReport.TotalBetsMade));
            
            #line default
            #line hidden
            this.Write(" bets</td>\r\n                </tr>\r\n                <tr>\r\n                    <td>" +
                    "How much time pass since you started to bet: </td>\r\n                    <td>");
            
            #line 16 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\TallyBehavior_Fragment.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ProfitAndLossReport.ElapseTimeSinceEaliestBet));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                </tr>\r\n            </tbody>\r\n        </table>\r\n    </div>\r" +
                    "\n</div>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
