// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LottoDataManager.Includes.Classes.Reports.Templates.Fragments.ReportBox
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\WinningBetTally_Fragment.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class WinningBetTally_Fragment : IndividualGameHTMLReportView
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"<div class=""outline-container"">
    <div class=""outline-title"">
        <span class=""title-keyword"">Winning Bet Tally</span>
        <span class=""title-description"">- Counting which digits are the most lucky numbers on your bets</span>
    </div>
    <div class=""outline-content"">
        <table class=""table-stats-style"" cellspacing=""0"">
            <thead>
                <th>Lotto Number</th>
                <th>Your total hits</th>
            </thead>
            <tbody>
                ");
            
            #line 14 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\WinningBetTally_Fragment.tt"
 foreach (var item in ProfitAndLossReport.AllBetsInTabularModeWinningBet) { 
            
            #line default
            #line hidden
            this.Write("                     <tr>\r\n                        <td>");
            
            #line 16 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\WinningBetTally_Fragment.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item[0]));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                        <td>");
            
            #line 17 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\WinningBetTally_Fragment.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item[1]));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                    </tr>\r\n                ");
            
            #line 19 "D:\Development\WorkSpace00002\LottoDataManager\Includes\Classes\Reports\Templates\Fragments\ReportBox\WinningBetTally_Fragment.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            </tbody>\r\n        </table>\r\n    </div>\r\n</div>\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
